# Generated by Django 4.2 on 2023-04-22 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.SmallIntegerField(default=0, verbose_name='سن')),
                ('gender', models.CharField(max_length=20, verbose_name='جنسیت')),
                ('wrist', models.FloatField(default=0, verbose_name='دور مچ')),
                ('height', models.FloatField(default=0, verbose_name='قد')),
                ('weight', models.FloatField(default=0, verbose_name='وزن')),
                ('waist', models.FloatField(default=0, verbose_name='دور کمر')),
                ('hips', models.FloatField(default=0, verbose_name='دور باسن')),
                ('child', models.BooleanField(default=False)),
                ('child_head', models.FloatField(default=0, verbose_name='دور سر بچه')),
                ('lowest_weight', models.FloatField(default=0, verbose_name='کمترین وزن در 2 یا 3 سال اخیر')),
                ('have_kids', models.BooleanField(default=False)),
                ('Hereditary_diseases', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('physical_activity', models.CharField(choices=[('low', 'خیلی کم'), ('2days', 'دو روز در هفته'), ('3days', 'سه روز در هفته'), ('4days', 'چهار روز در هفته'), ('5days', 'پنج روز در هفته یا بیشتر'), ('pro', 'ورزش کار حرفه ای')], max_length=40)),
                ('fasting_blood_sugar', models.FloatField(default=0, verbose_name='قند خون ناشتا')),
                ('blood_sugar', models.FloatField(default=0, verbose_name='قند خون')),
                ('HBA1C', models.FloatField(default=0)),
                ('triglyceride', models.FloatField(default=0)),
                ('Cholesterol', models.FloatField(default=0)),
                ('LDL', models.FloatField(default=0)),
                ('HDL', models.FloatField(default=0)),
                ('SGPT', models.FloatField(default=0)),
                ('SGOT', models.FloatField(default=0)),
                ('BUN', models.FloatField(default=0)),
                ('Creatinine', models.FloatField(default=0)),
                ('calcium_phosphorus', models.FloatField(default=0)),
                ('Sodium_potassium', models.FloatField(default=0)),
                ('D_3', models.FloatField(default=0)),
                ('iron', models.FloatField(default=0)),
                ('ferritin', models.FloatField(default=0)),
                ('TIBC', models.FloatField(default=0)),
                ('total_cal', models.FloatField(default=0)),
                ('total_protein', models.FloatField(default=0)),
                ('total_carbohydrate', models.FloatField(default=0)),
                ('total_fat', models.FloatField(default=0)),
                ('eating_habits', models.CharField(choices=[('low', 'خیلی کم'), ('mid', 'متوسط'), ('Relatively much', 'به نسبت زیاد'), ('too much', 'پر خور')], max_length=100, verbose_name='عادت های غذایی')),
                ('allergy', models.CharField(blank=True, max_length=100, null=True, verbose_name='آلرژی های غذایی')),
                ('Special_drugs', models.CharField(blank=True, max_length=100, null=True, verbose_name='دارو های خاص')),
            ],
        ),
    ]
